/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 4
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  anon_sym_HELP = 2,
  anon_sym_LF = 3,
  anon_sym_TYPE = 4,
  anon_sym_UNIT = 5,
  aux_sym_unit_line_token1 = 6,
  anon_sym_EOF = 7,
  anon_sym_counter = 8,
  anon_sym_gauge = 9,
  anon_sym_histogram = 10,
  anon_sym_gaugehistogram = 11,
  anon_sym_stateset = 12,
  anon_sym_info = 13,
  anon_sym_summary = 14,
  anon_sym_unknown = 15,
  sym_metric_name = 16,
  anon_sym_LBRACE = 17,
  anon_sym_COMMA = 18,
  anon_sym_RBRACE = 19,
  anon_sym_EQ = 20,
  anon_sym_DQUOTE = 21,
  sym__inf = 22,
  sym__nan = 23,
  sym__realnumber = 24,
  sym__escaped_string = 25,
  sym_source_file = 26,
  sym_metricfamily = 27,
  sym_help_line = 28,
  sym_type_line = 29,
  sym_unit_line = 30,
  sym__eof_line = 31,
  sym_metric_type = 32,
  sym_sample = 33,
  sym_exemplar = 34,
  sym_label_set = 35,
  sym_label = 36,
  sym_label_name = 37,
  sym_metric_value = 38,
  sym_timestamp = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_metricfamily_repeat1 = 41,
  aux_sym_label_set_repeat1 = 42,
  alias_sym_label_value = 43,
  alias_sym_metric = 44,
  alias_sym_metricset = 45,
  alias_sym_unit = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [anon_sym_HELP] = "HELP",
  [anon_sym_LF] = "\n",
  [anon_sym_TYPE] = "TYPE",
  [anon_sym_UNIT] = "UNIT",
  [aux_sym_unit_line_token1] = "unit_line_token1",
  [anon_sym_EOF] = "EOF",
  [anon_sym_counter] = "counter",
  [anon_sym_gauge] = "gauge",
  [anon_sym_histogram] = "histogram",
  [anon_sym_gaugehistogram] = "gaugehistogram",
  [anon_sym_stateset] = "stateset",
  [anon_sym_info] = "info",
  [anon_sym_summary] = "summary",
  [anon_sym_unknown] = "unknown",
  [sym_metric_name] = "metric_name",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_DQUOTE] = "\"",
  [sym__inf] = "_inf",
  [sym__nan] = "_nan",
  [sym__realnumber] = "_realnumber",
  [sym__escaped_string] = "metric_help",
  [sym_source_file] = "source_file",
  [sym_metricfamily] = "metricfamily",
  [sym_help_line] = "help_line",
  [sym_type_line] = "type_line",
  [sym_unit_line] = "unit_line",
  [sym__eof_line] = "eof",
  [sym_metric_type] = "metric_type",
  [sym_sample] = "sample",
  [sym_exemplar] = "exemplar",
  [sym_label_set] = "label_set",
  [sym_label] = "label",
  [sym_label_name] = "label_name",
  [sym_metric_value] = "metric_value",
  [sym_timestamp] = "timestamp",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_metricfamily_repeat1] = "metricfamily_repeat1",
  [aux_sym_label_set_repeat1] = "label_set_repeat1",
  [alias_sym_label_value] = "label_value",
  [alias_sym_metric] = "metric",
  [alias_sym_metricset] = "metricset",
  [alias_sym_unit] = "unit",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_HELP] = anon_sym_HELP,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_TYPE] = anon_sym_TYPE,
  [anon_sym_UNIT] = anon_sym_UNIT,
  [aux_sym_unit_line_token1] = aux_sym_unit_line_token1,
  [anon_sym_EOF] = anon_sym_EOF,
  [anon_sym_counter] = anon_sym_counter,
  [anon_sym_gauge] = anon_sym_gauge,
  [anon_sym_histogram] = anon_sym_histogram,
  [anon_sym_gaugehistogram] = anon_sym_gaugehistogram,
  [anon_sym_stateset] = anon_sym_stateset,
  [anon_sym_info] = anon_sym_info,
  [anon_sym_summary] = anon_sym_summary,
  [anon_sym_unknown] = anon_sym_unknown,
  [sym_metric_name] = sym_metric_name,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__inf] = sym__inf,
  [sym__nan] = sym__nan,
  [sym__realnumber] = sym__realnumber,
  [sym__escaped_string] = sym__escaped_string,
  [sym_source_file] = sym_source_file,
  [sym_metricfamily] = sym_metricfamily,
  [sym_help_line] = sym_help_line,
  [sym_type_line] = sym_type_line,
  [sym_unit_line] = sym_unit_line,
  [sym__eof_line] = sym__eof_line,
  [sym_metric_type] = sym_metric_type,
  [sym_sample] = sym_sample,
  [sym_exemplar] = sym_exemplar,
  [sym_label_set] = sym_label_set,
  [sym_label] = sym_label,
  [sym_label_name] = sym_label_name,
  [sym_metric_value] = sym_metric_value,
  [sym_timestamp] = sym_timestamp,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_metricfamily_repeat1] = aux_sym_metricfamily_repeat1,
  [aux_sym_label_set_repeat1] = aux_sym_label_set_repeat1,
  [alias_sym_label_value] = alias_sym_label_value,
  [alias_sym_metric] = alias_sym_metric,
  [alias_sym_metricset] = alias_sym_metricset,
  [alias_sym_unit] = alias_sym_unit,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HELP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TYPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UNIT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_unit_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EOF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_counter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gauge] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_histogram] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gaugehistogram] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stateset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_info] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_summary] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unknown] = {
    .visible = true,
    .named = false,
  },
  [sym_metric_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__inf] = {
    .visible = false,
    .named = true,
  },
  [sym__nan] = {
    .visible = false,
    .named = true,
  },
  [sym__realnumber] = {
    .visible = false,
    .named = true,
  },
  [sym__escaped_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_metricfamily] = {
    .visible = true,
    .named = true,
  },
  [sym_help_line] = {
    .visible = true,
    .named = true,
  },
  [sym_type_line] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_line] = {
    .visible = true,
    .named = true,
  },
  [sym__eof_line] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_type] = {
    .visible = true,
    .named = true,
  },
  [sym_sample] = {
    .visible = true,
    .named = true,
  },
  [sym_exemplar] = {
    .visible = true,
    .named = true,
  },
  [sym_label_set] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_value] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_metricfamily_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_label_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_label_value] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_metric] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_metricset] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_unit] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_metric,
  },
  [2] = {
    [0] = alias_sym_metricset,
  },
  [3] = {
    [2] = alias_sym_metric,
  },
  [4] = {
    [3] = alias_sym_metric,
  },
  [5] = {
    [3] = alias_sym_unit,
  },
  [6] = {
    [3] = alias_sym_label_value,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_source_file_repeat1, 2,
    aux_sym_source_file_repeat1,
    alias_sym_metricset,
  aux_sym_metricfamily_repeat1, 2,
    aux_sym_metricfamily_repeat1,
    alias_sym_metric,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(78);
      if (lookahead == '\n') ADVANCE(81);
      if (lookahead == ' ') SKIP(0);
      if (lookahead == '"') ADVANCE(99);
      if (lookahead == '#') ADVANCE(79);
      if (lookahead == ',') ADVANCE(96);
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == '=') ADVANCE(98);
      if (lookahead == 'E') ADVANCE(14);
      if (lookahead == 'H') ADVANCE(6);
      if (lookahead == 'I') ADVANCE(70);
      if (lookahead == 'T') ADVANCE(18);
      if (lookahead == 'U') ADVANCE(13);
      if (lookahead == 'c') ADVANCE(44);
      if (lookahead == 'g') ADVANCE(20);
      if (lookahead == 'h') ADVANCE(32);
      if (lookahead == 'i') ADVANCE(12);
      if (lookahead == 's') ADVANCE(58);
      if (lookahead == 'u') ADVANCE(39);
      if (lookahead == '{') ADVANCE(95);
      if (lookahead == '}') ADVANCE(97);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(5);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 1:
      if (lookahead == ' ') SKIP(1);
      if (lookahead == 'c') ADVANCE(44);
      if (lookahead == 'g') ADVANCE(20);
      if (lookahead == 'h') ADVANCE(32);
      if (lookahead == 'i') ADVANCE(41);
      if (lookahead == 's') ADVANCE(58);
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 2:
      if (lookahead == ' ') SKIP(2);
      if (lookahead == '#') ADVANCE(79);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 3:
      if (lookahead == ' ') SKIP(3);
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == '{') ADVANCE(95);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(5);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(70);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 4:
      if (lookahead == ' ') SKIP(4);
      if (lookahead == '}') ADVANCE(97);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 6:
      if (lookahead == 'E') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'E') ADVANCE(82);
      END_STATE();
    case 8:
      if (lookahead == 'F') ADVANCE(85);
      END_STATE();
    case 9:
      if (lookahead == 'F') ADVANCE(102);
      if (lookahead == 'f') ADVANCE(101);
      END_STATE();
    case 10:
      if (lookahead == 'I') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'L') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'N') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == 'N') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'O') ADVANCE(8);
      END_STATE();
    case 15:
      if (lookahead == 'P') ADVANCE(80);
      END_STATE();
    case 16:
      if (lookahead == 'P') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'T') ADVANCE(83);
      END_STATE();
    case 18:
      if (lookahead == 'Y') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(59);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 28:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 29:
      if (lookahead == 'g') ADVANCE(24);
      END_STATE();
    case 30:
      if (lookahead == 'g') ADVANCE(51);
      END_STATE();
    case 31:
      if (lookahead == 'g') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 33:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 34:
      if (lookahead == 'k') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'm') ADVANCE(88);
      END_STATE();
    case 36:
      if (lookahead == 'm') ADVANCE(89);
      END_STATE();
    case 37:
      if (lookahead == 'm') ADVANCE(38);
      END_STATE();
    case 38:
      if (lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(93);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(60);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(63);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(91);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 53:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 55:
      if (lookahead == 's') ADVANCE(61);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(21);
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 62:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 63:
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 64:
      if (lookahead == 'w') ADVANCE(40);
      END_STATE();
    case 65:
      if (lookahead == 'y') ADVANCE(92);
      END_STATE();
    case 66:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 67:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 68:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(102);
      END_STATE();
    case 69:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(73);
      END_STATE();
    case 70:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 71:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(103);
      END_STATE();
    case 72:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 73:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(74);
      END_STATE();
    case 74:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(100);
      END_STATE();
    case 75:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 76:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_HELP);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_TYPE);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_UNIT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_unit_line_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_EOF);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_counter);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_gauge);
      if (lookahead == 'h') ADVANCE(33);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_histogram);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_gaugehistogram);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_stateset);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_info);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_summary);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_unknown);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_metric_name);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym__inf);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym__inf);
      if (lookahead == 'o') ADVANCE(91);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym__inf);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym__nan);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym__realnumber);
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym__realnumber);
      if (lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym__realnumber);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym__escaped_string);
      if (lookahead == ' ') ADVANCE(107);
      if (lookahead == '\\') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(108);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym__escaped_string);
      if (lookahead == '\\') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(108);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 107},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 107},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_HELP] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_TYPE] = ACTIONS(1),
    [anon_sym_UNIT] = ACTIONS(1),
    [anon_sym_EOF] = ACTIONS(1),
    [anon_sym_counter] = ACTIONS(1),
    [anon_sym_gauge] = ACTIONS(1),
    [anon_sym_histogram] = ACTIONS(1),
    [anon_sym_gaugehistogram] = ACTIONS(1),
    [anon_sym_stateset] = ACTIONS(1),
    [anon_sym_info] = ACTIONS(1),
    [anon_sym_summary] = ACTIONS(1),
    [anon_sym_unknown] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__inf] = ACTIONS(1),
    [sym__nan] = ACTIONS(1),
    [sym__realnumber] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(61),
    [sym_metricfamily] = STATE(48),
    [sym_type_line] = STATE(3),
    [sym__eof_line] = STATE(55),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_POUND] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(7), 1,
      anon_sym_gauge,
    STATE(68), 1,
      sym_metric_type,
    ACTIONS(5), 7,
      anon_sym_counter,
      anon_sym_histogram,
      anon_sym_gaugehistogram,
      anon_sym_stateset,
      anon_sym_info,
      anon_sym_summary,
      anon_sym_unknown,
  [16] = 6,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      sym_metric_name,
    STATE(6), 1,
      sym_unit_line,
    STATE(9), 1,
      sym_help_line,
    STATE(11), 1,
      aux_sym_metricfamily_repeat1,
    STATE(43), 1,
      sym_sample,
  [35] = 4,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      sym_metric_value,
    STATE(13), 1,
      sym_label_set,
    ACTIONS(15), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [50] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(3), 1,
      sym_type_line,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(48), 1,
      sym_metricfamily,
    STATE(62), 1,
      sym__eof_line,
  [66] = 5,
    ACTIONS(11), 1,
      sym_metric_name,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(14), 1,
      aux_sym_metricfamily_repeat1,
    STATE(16), 1,
      sym_help_line,
    STATE(43), 1,
      sym_sample,
  [82] = 5,
    ACTIONS(19), 1,
      anon_sym_POUND,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym__realnumber,
    STATE(27), 1,
      sym_timestamp,
    STATE(53), 1,
      sym_exemplar,
  [98] = 5,
    ACTIONS(19), 1,
      anon_sym_POUND,
    ACTIONS(23), 1,
      sym__realnumber,
    ACTIONS(25), 1,
      anon_sym_LF,
    STATE(24), 1,
      sym_timestamp,
    STATE(54), 1,
      sym_exemplar,
  [114] = 4,
    ACTIONS(11), 1,
      sym_metric_name,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(14), 1,
      aux_sym_metricfamily_repeat1,
    STATE(43), 1,
      sym_sample,
  [127] = 4,
    ACTIONS(29), 1,
      anon_sym_POUND,
    STATE(3), 1,
      sym_type_line,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(48), 1,
      sym_metricfamily,
  [140] = 4,
    ACTIONS(11), 1,
      sym_metric_name,
    ACTIONS(32), 1,
      anon_sym_POUND,
    STATE(15), 1,
      aux_sym_metricfamily_repeat1,
    STATE(43), 1,
      sym_sample,
  [153] = 4,
    ACTIONS(34), 1,
      aux_sym_unit_line_token1,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      sym_label,
    STATE(72), 1,
      sym_label_name,
  [166] = 2,
    STATE(8), 1,
      sym_metric_value,
    ACTIONS(15), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [175] = 4,
    ACTIONS(11), 1,
      sym_metric_name,
    ACTIONS(38), 1,
      anon_sym_POUND,
    STATE(15), 1,
      aux_sym_metricfamily_repeat1,
    STATE(43), 1,
      sym_sample,
  [188] = 4,
    ACTIONS(40), 1,
      anon_sym_POUND,
    ACTIONS(42), 1,
      sym_metric_name,
    STATE(15), 1,
      aux_sym_metricfamily_repeat1,
    STATE(43), 1,
      sym_sample,
  [201] = 4,
    ACTIONS(11), 1,
      sym_metric_name,
    ACTIONS(45), 1,
      anon_sym_POUND,
    STATE(17), 1,
      aux_sym_metricfamily_repeat1,
    STATE(43), 1,
      sym_sample,
  [214] = 4,
    ACTIONS(11), 1,
      sym_metric_name,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(15), 1,
      aux_sym_metricfamily_repeat1,
    STATE(43), 1,
      sym_sample,
  [227] = 4,
    ACTIONS(34), 1,
      aux_sym_unit_line_token1,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      sym_label,
    STATE(72), 1,
      sym_label_name,
  [240] = 2,
    STATE(29), 1,
      sym_metric_value,
    ACTIONS(15), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [249] = 4,
    ACTIONS(34), 1,
      aux_sym_unit_line_token1,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      sym_label,
    STATE(72), 1,
      sym_label_name,
  [262] = 3,
    ACTIONS(53), 1,
      anon_sym_COMMA,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      aux_sym_label_set_repeat1,
  [272] = 1,
    ACTIONS(58), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [278] = 3,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(60), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_label_set_repeat1,
  [288] = 3,
    ACTIONS(19), 1,
      anon_sym_POUND,
    ACTIONS(62), 1,
      anon_sym_LF,
    STATE(65), 1,
      sym_exemplar,
  [298] = 1,
    ACTIONS(64), 3,
      anon_sym_POUND,
      anon_sym_LF,
      sym__realnumber,
  [304] = 1,
    ACTIONS(66), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [310] = 3,
    ACTIONS(19), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_LF,
    STATE(54), 1,
      sym_exemplar,
  [320] = 1,
    ACTIONS(68), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [326] = 3,
    ACTIONS(23), 1,
      sym__realnumber,
    ACTIONS(70), 1,
      anon_sym_LF,
    STATE(71), 1,
      sym_timestamp,
  [336] = 1,
    ACTIONS(72), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [342] = 3,
    ACTIONS(34), 1,
      aux_sym_unit_line_token1,
    STATE(46), 1,
      sym_label,
    STATE(72), 1,
      sym_label_name,
  [352] = 3,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      aux_sym_label_set_repeat1,
  [362] = 1,
    ACTIONS(78), 2,
      anon_sym_POUND,
      sym_metric_name,
  [367] = 1,
    ACTIONS(80), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [372] = 2,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 1,
      anon_sym_LF,
  [379] = 2,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_label_set,
  [386] = 1,
    ACTIONS(86), 2,
      anon_sym_POUND,
      sym_metric_name,
  [391] = 1,
    ACTIONS(88), 2,
      anon_sym_POUND,
      anon_sym_LF,
  [396] = 1,
    ACTIONS(90), 2,
      anon_sym_POUND,
      sym_metric_name,
  [401] = 2,
    ACTIONS(92), 1,
      anon_sym_HELP,
    ACTIONS(94), 1,
      anon_sym_UNIT,
  [408] = 2,
    ACTIONS(96), 1,
      anon_sym_TYPE,
    ACTIONS(98), 1,
      anon_sym_EOF,
  [415] = 1,
    ACTIONS(100), 2,
      anon_sym_POUND,
      sym_metric_name,
  [420] = 1,
    ACTIONS(102), 2,
      anon_sym_POUND,
      sym_metric_name,
  [425] = 1,
    ACTIONS(104), 2,
      anon_sym_POUND,
      sym_metric_name,
  [430] = 1,
    ACTIONS(106), 2,
      anon_sym_POUND,
      sym_metric_name,
  [435] = 1,
    ACTIONS(56), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [440] = 1,
    ACTIONS(108), 2,
      anon_sym_POUND,
      sym_metric_name,
  [445] = 1,
    ACTIONS(110), 1,
      anon_sym_POUND,
  [449] = 1,
    ACTIONS(112), 1,
      anon_sym_EQ,
  [453] = 1,
    ACTIONS(114), 1,
      aux_sym_unit_line_token1,
  [457] = 1,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
  [461] = 1,
    ACTIONS(118), 1,
      anon_sym_DQUOTE,
  [465] = 1,
    ACTIONS(25), 1,
      anon_sym_LF,
  [469] = 1,
    ACTIONS(62), 1,
      anon_sym_LF,
  [473] = 1,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
  [477] = 1,
    ACTIONS(122), 1,
      sym_metric_name,
  [481] = 1,
    ACTIONS(124), 1,
      sym_metric_name,
  [485] = 1,
    ACTIONS(126), 1,
      sym_metric_name,
  [489] = 1,
    ACTIONS(92), 1,
      anon_sym_HELP,
  [493] = 1,
    ACTIONS(128), 1,
      anon_sym_LF,
  [497] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [501] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [505] = 1,
    ACTIONS(134), 1,
      sym__escaped_string,
  [509] = 1,
    ACTIONS(136), 1,
      anon_sym_LF,
  [513] = 1,
    ACTIONS(138), 1,
      anon_sym_LF,
  [517] = 1,
    ACTIONS(96), 1,
      anon_sym_TYPE,
  [521] = 1,
    ACTIONS(140), 1,
      anon_sym_LF,
  [525] = 1,
    ACTIONS(142), 1,
      anon_sym_LF,
  [529] = 1,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
  [533] = 1,
    ACTIONS(146), 1,
      sym__escaped_string,
  [537] = 1,
    ACTIONS(148), 1,
      anon_sym_LF,
  [541] = 1,
    ACTIONS(150), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 16,
  [SMALL_STATE(4)] = 35,
  [SMALL_STATE(5)] = 50,
  [SMALL_STATE(6)] = 66,
  [SMALL_STATE(7)] = 82,
  [SMALL_STATE(8)] = 98,
  [SMALL_STATE(9)] = 114,
  [SMALL_STATE(10)] = 127,
  [SMALL_STATE(11)] = 140,
  [SMALL_STATE(12)] = 153,
  [SMALL_STATE(13)] = 166,
  [SMALL_STATE(14)] = 175,
  [SMALL_STATE(15)] = 188,
  [SMALL_STATE(16)] = 201,
  [SMALL_STATE(17)] = 214,
  [SMALL_STATE(18)] = 227,
  [SMALL_STATE(19)] = 240,
  [SMALL_STATE(20)] = 249,
  [SMALL_STATE(21)] = 262,
  [SMALL_STATE(22)] = 272,
  [SMALL_STATE(23)] = 278,
  [SMALL_STATE(24)] = 288,
  [SMALL_STATE(25)] = 298,
  [SMALL_STATE(26)] = 304,
  [SMALL_STATE(27)] = 310,
  [SMALL_STATE(28)] = 320,
  [SMALL_STATE(29)] = 326,
  [SMALL_STATE(30)] = 336,
  [SMALL_STATE(31)] = 342,
  [SMALL_STATE(32)] = 352,
  [SMALL_STATE(33)] = 362,
  [SMALL_STATE(34)] = 367,
  [SMALL_STATE(35)] = 372,
  [SMALL_STATE(36)] = 379,
  [SMALL_STATE(37)] = 386,
  [SMALL_STATE(38)] = 391,
  [SMALL_STATE(39)] = 396,
  [SMALL_STATE(40)] = 401,
  [SMALL_STATE(41)] = 408,
  [SMALL_STATE(42)] = 415,
  [SMALL_STATE(43)] = 420,
  [SMALL_STATE(44)] = 425,
  [SMALL_STATE(45)] = 430,
  [SMALL_STATE(46)] = 435,
  [SMALL_STATE(47)] = 440,
  [SMALL_STATE(48)] = 445,
  [SMALL_STATE(49)] = 449,
  [SMALL_STATE(50)] = 453,
  [SMALL_STATE(51)] = 457,
  [SMALL_STATE(52)] = 461,
  [SMALL_STATE(53)] = 465,
  [SMALL_STATE(54)] = 469,
  [SMALL_STATE(55)] = 473,
  [SMALL_STATE(56)] = 477,
  [SMALL_STATE(57)] = 481,
  [SMALL_STATE(58)] = 485,
  [SMALL_STATE(59)] = 489,
  [SMALL_STATE(60)] = 493,
  [SMALL_STATE(61)] = 497,
  [SMALL_STATE(62)] = 501,
  [SMALL_STATE(63)] = 505,
  [SMALL_STATE(64)] = 509,
  [SMALL_STATE(65)] = 513,
  [SMALL_STATE(66)] = 517,
  [SMALL_STATE(67)] = 521,
  [SMALL_STATE(68)] = 525,
  [SMALL_STATE(69)] = 529,
  [SMALL_STATE(70)] = 533,
  [SMALL_STATE(71)] = 537,
  [SMALL_STATE(72)] = 541,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metricfamily, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metricfamily, 2, 0, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metricfamily, 3, 0, 3),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_metricfamily_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metricfamily_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metricfamily, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metricfamily, 4, 0, 4),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_label_set_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_label_set_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_value, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 4, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exemplar, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 5, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 6, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 5, 0, 6),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eof_line, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timestamp, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_line, 5, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_metricfamily_repeat1, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_help_line, 5, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_line, 5, 0, 5),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 5, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_name, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eof_line, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [130] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_type, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exemplar, 4, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_openmetrics(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "openmetrics",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
