/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 61
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 2
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  anon_sym_HELP = 2,
  anon_sym_LF = 3,
  anon_sym_TYPE = 4,
  anon_sym_UNIT = 5,
  aux_sym_unit_line_token1 = 6,
  anon_sym_EOF = 7,
  anon_sym_counter = 8,
  anon_sym_gauge = 9,
  anon_sym_histogram = 10,
  anon_sym_gaugehistogram = 11,
  anon_sym_stateset = 12,
  anon_sym_info = 13,
  anon_sym_summary = 14,
  anon_sym_unknown = 15,
  sym_metric_name = 16,
  anon_sym_LBRACE = 17,
  anon_sym_COMMA = 18,
  anon_sym_RBRACE = 19,
  anon_sym_EQ = 20,
  anon_sym_DQUOTE = 21,
  sym__inf = 22,
  sym__nan = 23,
  sym__realnumber = 24,
  sym__escaped_string = 25,
  sym_source_file = 26,
  sym__line = 27,
  sym_help_line = 28,
  sym_type_line = 29,
  sym_unit_line = 30,
  sym_eof = 31,
  sym_metric_type = 32,
  sym_sample = 33,
  sym_exemplar = 34,
  sym_label_set = 35,
  sym_label = 36,
  sym_label_name = 37,
  sym_metric_value = 38,
  sym_timestamp = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_label_set_repeat1 = 41,
  alias_sym_label_value = 42,
  alias_sym_metric_unit = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [anon_sym_HELP] = "HELP",
  [anon_sym_LF] = "\n",
  [anon_sym_TYPE] = "TYPE",
  [anon_sym_UNIT] = "UNIT",
  [aux_sym_unit_line_token1] = "unit_line_token1",
  [anon_sym_EOF] = "EOF",
  [anon_sym_counter] = "counter",
  [anon_sym_gauge] = "gauge",
  [anon_sym_histogram] = "histogram",
  [anon_sym_gaugehistogram] = "gaugehistogram",
  [anon_sym_stateset] = "stateset",
  [anon_sym_info] = "info",
  [anon_sym_summary] = "summary",
  [anon_sym_unknown] = "unknown",
  [sym_metric_name] = "metric_name",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_DQUOTE] = "\"",
  [sym__inf] = "_inf",
  [sym__nan] = "_nan",
  [sym__realnumber] = "_realnumber",
  [sym__escaped_string] = "metric_help",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_help_line] = "help_line",
  [sym_type_line] = "type_line",
  [sym_unit_line] = "unit_line",
  [sym_eof] = "eof",
  [sym_metric_type] = "metric_type",
  [sym_sample] = "sample",
  [sym_exemplar] = "exemplar",
  [sym_label_set] = "label_set",
  [sym_label] = "label",
  [sym_label_name] = "label_name",
  [sym_metric_value] = "metric_value",
  [sym_timestamp] = "timestamp",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_label_set_repeat1] = "label_set_repeat1",
  [alias_sym_label_value] = "label_value",
  [alias_sym_metric_unit] = "metric_unit",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_HELP] = anon_sym_HELP,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_TYPE] = anon_sym_TYPE,
  [anon_sym_UNIT] = anon_sym_UNIT,
  [aux_sym_unit_line_token1] = aux_sym_unit_line_token1,
  [anon_sym_EOF] = anon_sym_EOF,
  [anon_sym_counter] = anon_sym_counter,
  [anon_sym_gauge] = anon_sym_gauge,
  [anon_sym_histogram] = anon_sym_histogram,
  [anon_sym_gaugehistogram] = anon_sym_gaugehistogram,
  [anon_sym_stateset] = anon_sym_stateset,
  [anon_sym_info] = anon_sym_info,
  [anon_sym_summary] = anon_sym_summary,
  [anon_sym_unknown] = anon_sym_unknown,
  [sym_metric_name] = sym_metric_name,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__inf] = sym__inf,
  [sym__nan] = sym__nan,
  [sym__realnumber] = sym__realnumber,
  [sym__escaped_string] = sym__escaped_string,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_help_line] = sym_help_line,
  [sym_type_line] = sym_type_line,
  [sym_unit_line] = sym_unit_line,
  [sym_eof] = sym_eof,
  [sym_metric_type] = sym_metric_type,
  [sym_sample] = sym_sample,
  [sym_exemplar] = sym_exemplar,
  [sym_label_set] = sym_label_set,
  [sym_label] = sym_label,
  [sym_label_name] = sym_label_name,
  [sym_metric_value] = sym_metric_value,
  [sym_timestamp] = sym_timestamp,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_label_set_repeat1] = aux_sym_label_set_repeat1,
  [alias_sym_label_value] = alias_sym_label_value,
  [alias_sym_metric_unit] = alias_sym_metric_unit,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HELP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TYPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UNIT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_unit_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EOF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_counter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gauge] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_histogram] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gaugehistogram] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stateset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_info] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_summary] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unknown] = {
    .visible = true,
    .named = false,
  },
  [sym_metric_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__inf] = {
    .visible = false,
    .named = true,
  },
  [sym__nan] = {
    .visible = false,
    .named = true,
  },
  [sym__realnumber] = {
    .visible = false,
    .named = true,
  },
  [sym__escaped_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_help_line] = {
    .visible = true,
    .named = true,
  },
  [sym_type_line] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_line] = {
    .visible = true,
    .named = true,
  },
  [sym_eof] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_type] = {
    .visible = true,
    .named = true,
  },
  [sym_sample] = {
    .visible = true,
    .named = true,
  },
  [sym_exemplar] = {
    .visible = true,
    .named = true,
  },
  [sym_label_set] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_value] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_label_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_label_value] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_metric_unit] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [3] = alias_sym_metric_unit,
  },
  [2] = {
    [3] = alias_sym_label_value,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(78);
      if (lookahead == '\n') ADVANCE(81);
      if (lookahead == ' ') SKIP(0);
      if (lookahead == '"') ADVANCE(99);
      if (lookahead == '#') ADVANCE(79);
      if (lookahead == ',') ADVANCE(96);
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == '=') ADVANCE(98);
      if (lookahead == 'E') ADVANCE(14);
      if (lookahead == 'H') ADVANCE(6);
      if (lookahead == 'I') ADVANCE(70);
      if (lookahead == 'T') ADVANCE(18);
      if (lookahead == 'U') ADVANCE(13);
      if (lookahead == 'c') ADVANCE(44);
      if (lookahead == 'g') ADVANCE(20);
      if (lookahead == 'h') ADVANCE(32);
      if (lookahead == 'i') ADVANCE(12);
      if (lookahead == 's') ADVANCE(58);
      if (lookahead == 'u') ADVANCE(39);
      if (lookahead == '{') ADVANCE(95);
      if (lookahead == '}') ADVANCE(97);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(5);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 1:
      if (lookahead == ' ') SKIP(1);
      if (lookahead == '#') ADVANCE(79);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 2:
      if (lookahead == ' ') SKIP(2);
      if (lookahead == 'c') ADVANCE(44);
      if (lookahead == 'g') ADVANCE(20);
      if (lookahead == 'h') ADVANCE(32);
      if (lookahead == 'i') ADVANCE(41);
      if (lookahead == 's') ADVANCE(58);
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 3:
      if (lookahead == ' ') SKIP(3);
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == '{') ADVANCE(95);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(5);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(70);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 4:
      if (lookahead == ' ') SKIP(4);
      if (lookahead == '}') ADVANCE(97);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 6:
      if (lookahead == 'E') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'E') ADVANCE(82);
      END_STATE();
    case 8:
      if (lookahead == 'F') ADVANCE(85);
      END_STATE();
    case 9:
      if (lookahead == 'F') ADVANCE(102);
      if (lookahead == 'f') ADVANCE(101);
      END_STATE();
    case 10:
      if (lookahead == 'I') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'L') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'N') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == 'N') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'O') ADVANCE(8);
      END_STATE();
    case 15:
      if (lookahead == 'P') ADVANCE(80);
      END_STATE();
    case 16:
      if (lookahead == 'P') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'T') ADVANCE(83);
      END_STATE();
    case 18:
      if (lookahead == 'Y') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(59);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 28:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 29:
      if (lookahead == 'g') ADVANCE(24);
      END_STATE();
    case 30:
      if (lookahead == 'g') ADVANCE(51);
      END_STATE();
    case 31:
      if (lookahead == 'g') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 33:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 34:
      if (lookahead == 'k') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'm') ADVANCE(88);
      END_STATE();
    case 36:
      if (lookahead == 'm') ADVANCE(89);
      END_STATE();
    case 37:
      if (lookahead == 'm') ADVANCE(38);
      END_STATE();
    case 38:
      if (lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(93);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(60);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(63);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(91);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 53:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 55:
      if (lookahead == 's') ADVANCE(61);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(21);
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 62:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 63:
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 64:
      if (lookahead == 'w') ADVANCE(40);
      END_STATE();
    case 65:
      if (lookahead == 'y') ADVANCE(92);
      END_STATE();
    case 66:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 67:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 68:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(102);
      END_STATE();
    case 69:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(73);
      END_STATE();
    case 70:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 71:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(103);
      END_STATE();
    case 72:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 73:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(74);
      END_STATE();
    case 74:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(100);
      END_STATE();
    case 75:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 76:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_HELP);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_TYPE);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_UNIT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_unit_line_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_EOF);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_counter);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_gauge);
      if (lookahead == 'h') ADVANCE(33);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_histogram);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_gaugehistogram);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_stateset);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_info);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_summary);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_unknown);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_metric_name);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym__inf);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym__inf);
      if (lookahead == 'o') ADVANCE(91);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym__inf);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym__nan);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym__realnumber);
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym__realnumber);
      if (lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym__realnumber);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym__escaped_string);
      if (lookahead == ' ') ADVANCE(107);
      if (lookahead == '\\') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(108);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym__escaped_string);
      if (lookahead == '\\') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(108);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 107},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 107},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_HELP] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_TYPE] = ACTIONS(1),
    [anon_sym_UNIT] = ACTIONS(1),
    [anon_sym_EOF] = ACTIONS(1),
    [anon_sym_counter] = ACTIONS(1),
    [anon_sym_gauge] = ACTIONS(1),
    [anon_sym_histogram] = ACTIONS(1),
    [anon_sym_gaugehistogram] = ACTIONS(1),
    [anon_sym_stateset] = ACTIONS(1),
    [anon_sym_info] = ACTIONS(1),
    [anon_sym_summary] = ACTIONS(1),
    [anon_sym_unknown] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__inf] = ACTIONS(1),
    [sym__nan] = ACTIONS(1),
    [sym__realnumber] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(43),
    [sym__line] = STATE(2),
    [sym_help_line] = STATE(2),
    [sym_type_line] = STATE(2),
    [sym_unit_line] = STATE(2),
    [sym_eof] = STATE(56),
    [sym_sample] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_POUND] = ACTIONS(3),
    [sym_metric_name] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym_metric_name,
    STATE(55), 1,
      sym_eof,
    STATE(4), 6,
      sym__line,
      sym_help_line,
      sym_type_line,
      sym_unit_line,
      sym_sample,
      aux_sym_source_file_repeat1,
  [18] = 3,
    ACTIONS(9), 1,
      anon_sym_gauge,
    STATE(52), 1,
      sym_metric_type,
    ACTIONS(7), 7,
      anon_sym_counter,
      anon_sym_histogram,
      anon_sym_gaugehistogram,
      anon_sym_stateset,
      anon_sym_info,
      anon_sym_summary,
      anon_sym_unknown,
  [34] = 3,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(14), 1,
      sym_metric_name,
    STATE(4), 6,
      sym__line,
      sym_help_line,
      sym_type_line,
      sym_unit_line,
      sym_sample,
      aux_sym_source_file_repeat1,
  [49] = 4,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    STATE(6), 1,
      sym_metric_value,
    STATE(11), 1,
      sym_label_set,
    ACTIONS(19), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [64] = 5,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(25), 1,
      sym__realnumber,
    STATE(17), 1,
      sym_timestamp,
    STATE(45), 1,
      sym_exemplar,
  [80] = 5,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      sym__realnumber,
    ACTIONS(27), 1,
      anon_sym_LF,
    STATE(22), 1,
      sym_timestamp,
    STATE(41), 1,
      sym_exemplar,
  [96] = 4,
    ACTIONS(29), 1,
      aux_sym_unit_line_token1,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      sym_label,
    STATE(58), 1,
      sym_label_name,
  [109] = 4,
    ACTIONS(29), 1,
      aux_sym_unit_line_token1,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      sym_label,
    STATE(58), 1,
      sym_label_name,
  [122] = 4,
    ACTIONS(29), 1,
      aux_sym_unit_line_token1,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      sym_label,
    STATE(58), 1,
      sym_label_name,
  [135] = 2,
    STATE(7), 1,
      sym_metric_value,
    ACTIONS(19), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [144] = 4,
    ACTIONS(37), 1,
      anon_sym_HELP,
    ACTIONS(39), 1,
      anon_sym_TYPE,
    ACTIONS(41), 1,
      anon_sym_UNIT,
    ACTIONS(43), 1,
      anon_sym_EOF,
  [157] = 2,
    STATE(26), 1,
      sym_metric_value,
    ACTIONS(19), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [166] = 1,
    ACTIONS(45), 3,
      anon_sym_POUND,
      anon_sym_LF,
      sym__realnumber,
  [172] = 1,
    ACTIONS(47), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [178] = 3,
    ACTIONS(49), 1,
      anon_sym_COMMA,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym_label_set_repeat1,
  [188] = 3,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_LF,
    STATE(41), 1,
      sym_exemplar,
  [198] = 3,
    ACTIONS(37), 1,
      anon_sym_HELP,
    ACTIONS(39), 1,
      anon_sym_TYPE,
    ACTIONS(41), 1,
      anon_sym_UNIT,
  [208] = 1,
    ACTIONS(53), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [214] = 3,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(55), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym_label_set_repeat1,
  [224] = 3,
    ACTIONS(29), 1,
      aux_sym_unit_line_token1,
    STATE(32), 1,
      sym_label,
    STATE(58), 1,
      sym_label_name,
  [234] = 3,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(57), 1,
      anon_sym_LF,
    STATE(53), 1,
      sym_exemplar,
  [244] = 1,
    ACTIONS(59), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [250] = 3,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      aux_sym_label_set_repeat1,
  [260] = 1,
    ACTIONS(66), 3,
      sym__inf,
      sym__nan,
      sym__realnumber,
  [266] = 3,
    ACTIONS(25), 1,
      sym__realnumber,
    ACTIONS(68), 1,
      anon_sym_LF,
    STATE(59), 1,
      sym_timestamp,
  [276] = 1,
    ACTIONS(70), 2,
      anon_sym_POUND,
      anon_sym_LF,
  [281] = 1,
    ACTIONS(72), 2,
      anon_sym_POUND,
      sym_metric_name,
  [286] = 2,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym_label_set,
  [293] = 2,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      anon_sym_LF,
  [300] = 1,
    ACTIONS(78), 2,
      anon_sym_POUND,
      sym_metric_name,
  [305] = 1,
    ACTIONS(64), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [310] = 1,
    ACTIONS(80), 2,
      anon_sym_POUND,
      sym_metric_name,
  [315] = 1,
    ACTIONS(82), 2,
      anon_sym_POUND,
      sym_metric_name,
  [320] = 1,
    ACTIONS(84), 2,
      anon_sym_POUND,
      sym_metric_name,
  [325] = 1,
    ACTIONS(86), 2,
      anon_sym_POUND,
      sym_metric_name,
  [330] = 1,
    ACTIONS(88), 2,
      anon_sym_POUND,
      sym_metric_name,
  [335] = 1,
    ACTIONS(90), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [340] = 1,
    ACTIONS(92), 1,
      anon_sym_LF,
  [344] = 1,
    ACTIONS(94), 1,
      sym_metric_name,
  [348] = 1,
    ACTIONS(57), 1,
      anon_sym_LF,
  [352] = 1,
    ACTIONS(96), 1,
      sym__escaped_string,
  [356] = 1,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
  [360] = 1,
    ACTIONS(100), 1,
      aux_sym_unit_line_token1,
  [364] = 1,
    ACTIONS(27), 1,
      anon_sym_LF,
  [368] = 1,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
  [372] = 1,
    ACTIONS(104), 1,
      anon_sym_EQ,
  [376] = 1,
    ACTIONS(106), 1,
      anon_sym_LF,
  [380] = 1,
    ACTIONS(108), 1,
      sym_metric_name,
  [384] = 1,
    ACTIONS(110), 1,
      sym_metric_name,
  [388] = 1,
    ACTIONS(112), 1,
      sym__escaped_string,
  [392] = 1,
    ACTIONS(114), 1,
      anon_sym_LF,
  [396] = 1,
    ACTIONS(116), 1,
      anon_sym_LF,
  [400] = 1,
    ACTIONS(118), 1,
      anon_sym_LF,
  [404] = 1,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
  [408] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [412] = 1,
    ACTIONS(124), 1,
      anon_sym_DQUOTE,
  [416] = 1,
    ACTIONS(126), 1,
      anon_sym_EQ,
  [420] = 1,
    ACTIONS(128), 1,
      anon_sym_LF,
  [424] = 1,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 34,
  [SMALL_STATE(5)] = 49,
  [SMALL_STATE(6)] = 64,
  [SMALL_STATE(7)] = 80,
  [SMALL_STATE(8)] = 96,
  [SMALL_STATE(9)] = 109,
  [SMALL_STATE(10)] = 122,
  [SMALL_STATE(11)] = 135,
  [SMALL_STATE(12)] = 144,
  [SMALL_STATE(13)] = 157,
  [SMALL_STATE(14)] = 166,
  [SMALL_STATE(15)] = 172,
  [SMALL_STATE(16)] = 178,
  [SMALL_STATE(17)] = 188,
  [SMALL_STATE(18)] = 198,
  [SMALL_STATE(19)] = 208,
  [SMALL_STATE(20)] = 214,
  [SMALL_STATE(21)] = 224,
  [SMALL_STATE(22)] = 234,
  [SMALL_STATE(23)] = 244,
  [SMALL_STATE(24)] = 250,
  [SMALL_STATE(25)] = 260,
  [SMALL_STATE(26)] = 266,
  [SMALL_STATE(27)] = 276,
  [SMALL_STATE(28)] = 281,
  [SMALL_STATE(29)] = 286,
  [SMALL_STATE(30)] = 293,
  [SMALL_STATE(31)] = 300,
  [SMALL_STATE(32)] = 305,
  [SMALL_STATE(33)] = 310,
  [SMALL_STATE(34)] = 315,
  [SMALL_STATE(35)] = 320,
  [SMALL_STATE(36)] = 325,
  [SMALL_STATE(37)] = 330,
  [SMALL_STATE(38)] = 335,
  [SMALL_STATE(39)] = 340,
  [SMALL_STATE(40)] = 344,
  [SMALL_STATE(41)] = 348,
  [SMALL_STATE(42)] = 352,
  [SMALL_STATE(43)] = 356,
  [SMALL_STATE(44)] = 360,
  [SMALL_STATE(45)] = 364,
  [SMALL_STATE(46)] = 368,
  [SMALL_STATE(47)] = 372,
  [SMALL_STATE(48)] = 376,
  [SMALL_STATE(49)] = 380,
  [SMALL_STATE(50)] = 384,
  [SMALL_STATE(51)] = 388,
  [SMALL_STATE(52)] = 392,
  [SMALL_STATE(53)] = 396,
  [SMALL_STATE(54)] = 400,
  [SMALL_STATE(55)] = 404,
  [SMALL_STATE(56)] = 408,
  [SMALL_STATE(57)] = 412,
  [SMALL_STATE(58)] = 416,
  [SMALL_STATE(59)] = 420,
  [SMALL_STATE(60)] = 424,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_value, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 4, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_label_set_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_label_set_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 5, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exemplar, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timestamp, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eof, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_line, 5, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_help_line, 5, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 5, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_line, 5, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 4, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 6, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 5, 0, 2),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_type, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [98] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eof, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_name, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exemplar, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_openmetrics(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "openmetrics",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
